#!/bin/zsh
# Change zsh to bash if you only have bash installed

if [[ $OSTYPE == "linux-gnu"* ]]; then
	sass --no-source-map --watch scss:assets/css
else
	sass.bat --no-source-map --watch scss:assets/css
fi
